name: Kubebuilder CI
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    uses: konfidence-project/.github/.github/workflows/golang-lint.yaml@v1
    secrets: inherit
  test:
    name: Test
    uses: konfidence-project/.github/.github/workflows/kubebuilder-test.yaml@v1
    secrets: inherit
    with:
      with-kind-cluster: false
      install-crds: false
  build-and-release:
    name: Build Container Image
    # Only run on main branch or pull requests
    if:  github.event_name == 'pull_request'
    uses: konfidence-project/.github/.github/workflows/kubebuilder-container-build-and-release.yaml@v1
    secrets: inherit
    with: 
      push: false

    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      attestations: write
      id-token: write
