// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/konfidence-project/kubernetes-landscape-orchestrator/internal/fluxdeployer/internal/fluxcd (interfaces: FluxKustomizeReconciler,FluxKustomizeWorkloadReconciler)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_flux_kustomize_reconciler.go -package=mocks github.com/konfidence-project/kubernetes-landscape-orchestrator/internal/fluxdeployer/internal/fluxcd FluxKustomizeReconciler,FluxKustomizeWorkloadReconciler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	meta "github.com/fluxcd/pkg/apis/meta"
	v1alpha1 "github.com/konfidence-project/konfidence/api/v1alpha1"
	fluxcd "github.com/konfidence-project/kubernetes-landscape-orchestrator/internal/fluxdeployer/internal/fluxcd"
	gomock "go.uber.org/mock/gomock"
)

// MockFluxKustomizeReconciler is a mock of FluxKustomizeReconciler interface.
type MockFluxKustomizeReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockFluxKustomizeReconcilerMockRecorder
	isgomock struct{}
}

// MockFluxKustomizeReconcilerMockRecorder is the mock recorder for MockFluxKustomizeReconciler.
type MockFluxKustomizeReconcilerMockRecorder struct {
	mock *MockFluxKustomizeReconciler
}

// NewMockFluxKustomizeReconciler creates a new mock instance.
func NewMockFluxKustomizeReconciler(ctrl *gomock.Controller) *MockFluxKustomizeReconciler {
	mock := &MockFluxKustomizeReconciler{ctrl: ctrl}
	mock.recorder = &MockFluxKustomizeReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFluxKustomizeReconciler) EXPECT() *MockFluxKustomizeReconcilerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockFluxKustomizeReconciler) Reconcile(ctx context.Context, deployment *v1alpha1.ArtifactDeployment, kustomizeResource *fluxcd.KustomizeResource) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, deployment, kustomizeResource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockFluxKustomizeReconcilerMockRecorder) Reconcile(ctx, deployment, kustomizeResource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockFluxKustomizeReconciler)(nil).Reconcile), ctx, deployment, kustomizeResource)
}

// MockFluxKustomizeWorkloadReconciler is a mock of FluxKustomizeWorkloadReconciler interface.
type MockFluxKustomizeWorkloadReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockFluxKustomizeWorkloadReconcilerMockRecorder
	isgomock struct{}
}

// MockFluxKustomizeWorkloadReconcilerMockRecorder is the mock recorder for MockFluxKustomizeWorkloadReconciler.
type MockFluxKustomizeWorkloadReconcilerMockRecorder struct {
	mock *MockFluxKustomizeWorkloadReconciler
}

// NewMockFluxKustomizeWorkloadReconciler creates a new mock instance.
func NewMockFluxKustomizeWorkloadReconciler(ctrl *gomock.Controller) *MockFluxKustomizeWorkloadReconciler {
	mock := &MockFluxKustomizeWorkloadReconciler{ctrl: ctrl}
	mock.recorder = &MockFluxKustomizeWorkloadReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFluxKustomizeWorkloadReconciler) EXPECT() *MockFluxKustomizeWorkloadReconcilerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockFluxKustomizeWorkloadReconciler) Reconcile(ctx context.Context, deployment *v1alpha1.ArtifactDeployment, kustomizeResource *fluxcd.KustomizeResource, kubeConfig *meta.KubeConfigReference) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, deployment, kustomizeResource, kubeConfig)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockFluxKustomizeWorkloadReconcilerMockRecorder) Reconcile(ctx, deployment, kustomizeResource, kubeConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockFluxKustomizeWorkloadReconciler)(nil).Reconcile), ctx, deployment, kustomizeResource, kubeConfig)
}
