// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/konfidence-project/kubernetes-landscape-orchestrator/internal/fluxdeployer/internal/fluxcd (interfaces: FluxHelmReconciler,FluxHelmWorkloadReconciler)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_flux_helm_reconciler.go -package=mocks github.com/konfidence-project/kubernetes-landscape-orchestrator/internal/fluxdeployer/internal/fluxcd FluxHelmReconciler,FluxHelmWorkloadReconciler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	meta "github.com/fluxcd/pkg/apis/meta"
	v1alpha1 "github.com/konfidence-project/konfidence/api/v1alpha1"
	fluxcd "github.com/konfidence-project/kubernetes-landscape-orchestrator/internal/fluxdeployer/internal/fluxcd"
	gomock "go.uber.org/mock/gomock"
)

// MockFluxHelmReconciler is a mock of FluxHelmReconciler interface.
type MockFluxHelmReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockFluxHelmReconcilerMockRecorder
	isgomock struct{}
}

// MockFluxHelmReconcilerMockRecorder is the mock recorder for MockFluxHelmReconciler.
type MockFluxHelmReconcilerMockRecorder struct {
	mock *MockFluxHelmReconciler
}

// NewMockFluxHelmReconciler creates a new mock instance.
func NewMockFluxHelmReconciler(ctrl *gomock.Controller) *MockFluxHelmReconciler {
	mock := &MockFluxHelmReconciler{ctrl: ctrl}
	mock.recorder = &MockFluxHelmReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFluxHelmReconciler) EXPECT() *MockFluxHelmReconcilerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockFluxHelmReconciler) Reconcile(ctx context.Context, deployment *v1alpha1.ArtifactDeployment, helmChartResource *fluxcd.HelmChartResource) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, deployment, helmChartResource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockFluxHelmReconcilerMockRecorder) Reconcile(ctx, deployment, helmChartResource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockFluxHelmReconciler)(nil).Reconcile), ctx, deployment, helmChartResource)
}

// MockFluxHelmWorkloadReconciler is a mock of FluxHelmWorkloadReconciler interface.
type MockFluxHelmWorkloadReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockFluxHelmWorkloadReconcilerMockRecorder
	isgomock struct{}
}

// MockFluxHelmWorkloadReconcilerMockRecorder is the mock recorder for MockFluxHelmWorkloadReconciler.
type MockFluxHelmWorkloadReconcilerMockRecorder struct {
	mock *MockFluxHelmWorkloadReconciler
}

// NewMockFluxHelmWorkloadReconciler creates a new mock instance.
func NewMockFluxHelmWorkloadReconciler(ctrl *gomock.Controller) *MockFluxHelmWorkloadReconciler {
	mock := &MockFluxHelmWorkloadReconciler{ctrl: ctrl}
	mock.recorder = &MockFluxHelmWorkloadReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFluxHelmWorkloadReconciler) EXPECT() *MockFluxHelmWorkloadReconcilerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockFluxHelmWorkloadReconciler) Reconcile(ctx context.Context, deployment *v1alpha1.ArtifactDeployment, helmChartResource *fluxcd.HelmChartResource, kubeConfig *meta.KubeConfigReference) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, deployment, helmChartResource, kubeConfig)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockFluxHelmWorkloadReconcilerMockRecorder) Reconcile(ctx, deployment, helmChartResource, kubeConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockFluxHelmWorkloadReconciler)(nil).Reconcile), ctx, deployment, helmChartResource, kubeConfig)
}
