---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{- include "kubernetes-landscape-orchestrator.labels" . | nindent 4 }}
  name: {{ include "kubernetes-landscape-orchestrator.fullname" . }}-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfidence.cloud
  resources:
  - activationtaskexecutions
  - artifactdeployments
  - taskexecutions
  - vectoractivations
  - vectordeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfidence.cloud
  resources:
  - activationtaskexecutions/status
  - artifactdeployments/status
  - taskexecutions/status
  - vectoractivations/status
  - vectorassignments/status
  - vectordata/status
  - vectordeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - konfidence.cloud
  resources:
  - artifactdeployments/finalizers
  - taskexecutions/finalizers
  - vectordata/finalizers
  verbs:
  - update
- apiGroups:
  - konfidence.cloud
  resources:
  - vectorassignments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfidence.cloud
  resources:
  - vectordata
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  - helmrepositories
  - ocirepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
