{{- if ne (.Values.controller.metricsBindAddress | toString) "0" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-landscape-orchestrator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-landscape-orchestrator.labels" . | nindent 4 }}
    konfidence.cloud/service: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ include "kubernetes-landscape-orchestrator.bindAddressPort" .Values.controller.metricsBindAddress }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "kubernetes-landscape-orchestrator.selectorLabels" . | nindent 4 }}
{{- end }}
