---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: landscape-kubernetes-activation-execution-manager
rules:
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - activationtaskexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - activationtaskexecutions/status
  verbs:
  - get
  - patch
  - update
