name: Kubebuilder CI
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: konfidence-project/.github/.github/workflows/kubebuilder-ci-pipeline.yaml@v3
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      attestations: write
      id-token: write
    with:
      before-tests: make generate-test-crds
