{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vector-data-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector-data-service.labels" . | nindent 4 }}
spec:
  {{- if ne .Values.podDisruptionBudget.minAvailable nil }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if ne .Values.podDisruptionBudget.maxUnavailable nil }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  {{- fail "podDisruptionBudget.enabled is true but neither minAvailable nor maxUnavailable is set" }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vector-data-service.selectorLabels" . | nindent 6 }}
{{- end }}
