apiVersion: v2
name: kubernetes-landscape-orchestrator
description: Konfidence Kubernetes Landscape Orchestrator operator.
type: application
version: 0.0.0
appVersion: 0.0.0
kubeVersion: '>=1.27.0-0'
keywords:
  - konfidence
  - kubernetes-landscape-orchestrator
  - controller
  - operator
home: https://github.com/konfidence-project/kubernetes-landscape-orchestrator
sources:
  - https://github.com/konfidence-project/kubernetes-landscape-orchestrator
maintainers:
  - name: Konfidence maintainers
