// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/konfidence-project/kubernetes-landscape-orchestrator/internal/fluxdeployer/internal/controller (interfaces: StatusUpdater)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_status_updater.go -package=mocks github.com/konfidence-project/kubernetes-landscape-orchestrator/internal/fluxdeployer/internal/controller StatusUpdater
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/konfidence-project/konfidence/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusUpdater is a mock of StatusUpdater interface.
type MockStatusUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockStatusUpdaterMockRecorder
	isgomock struct{}
}

// MockStatusUpdaterMockRecorder is the mock recorder for MockStatusUpdater.
type MockStatusUpdaterMockRecorder struct {
	mock *MockStatusUpdater
}

// NewMockStatusUpdater creates a new mock instance.
func NewMockStatusUpdater(ctrl *gomock.Controller) *MockStatusUpdater {
	mock := &MockStatusUpdater{ctrl: ctrl}
	mock.recorder = &MockStatusUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusUpdater) EXPECT() *MockStatusUpdaterMockRecorder {
	return m.recorder
}

// MutateStatus mocks base method.
func (m *MockStatusUpdater) MutateStatus(ctx context.Context, deployment *v1alpha1.ArtifactDeployment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MutateStatus", ctx, deployment)
	ret0, _ := ret[0].(error)
	return ret0
}

// MutateStatus indicates an expected call of MutateStatus.
func (mr *MockStatusUpdaterMockRecorder) MutateStatus(ctx, deployment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MutateStatus", reflect.TypeOf((*MockStatusUpdater)(nil).MutateStatus), ctx, deployment)
}
