// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/konfidence-project/konfidence/pkg/deployer (interfaces: ArtifactDeployer)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_artifact_deployer.go -package=mocks github.com/konfidence-project/konfidence/pkg/deployer ArtifactDeployer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/konfidence-project/konfidence/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockArtifactDeployer is a mock of ArtifactDeployer interface.
type MockArtifactDeployer struct {
	ctrl     *gomock.Controller
	recorder *MockArtifactDeployerMockRecorder
	isgomock struct{}
}

// MockArtifactDeployerMockRecorder is the mock recorder for MockArtifactDeployer.
type MockArtifactDeployerMockRecorder struct {
	mock *MockArtifactDeployer
}

// NewMockArtifactDeployer creates a new mock instance.
func NewMockArtifactDeployer(ctrl *gomock.Controller) *MockArtifactDeployer {
	mock := &MockArtifactDeployer{ctrl: ctrl}
	mock.recorder = &MockArtifactDeployerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtifactDeployer) EXPECT() *MockArtifactDeployerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockArtifactDeployer) Reconcile(ctx context.Context, deployment *v1alpha1.ArtifactDeployment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, deployment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockArtifactDeployerMockRecorder) Reconcile(ctx, deployment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockArtifactDeployer)(nil).Reconcile), ctx, deployment)
}
