name: Dependabot Automerge

on: pull_request_target

jobs:
  automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: read
    uses: konfidence-project/.github/.github/workflows/dependabot-automerge.yaml@main
    secrets: inherit
