name: Pre-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Pre-release version (e.g. 1.0.0-rc.1)'
        required: true
        type: string

jobs:
  tag:
    name: Create Pre-release Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: konfidence-project/.github/.github/actions/github-repo-access@v4
        with:
          client-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.KONFIDENCE_PROJECT_REPO_ACCESS_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}

      - name: Create and push tag
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}