name: Release PR

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    name: Release PR
    permissions:
      contents: write
      pull-requests: write
    uses: konfidence-project/.github/.github/workflows/release-please.yaml@v4
    secrets: inherit
