apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: landscape-kubernetes-task-execution-controller
    app.kubernetes.io/managed-by: kustomize
  name: landscape-kubernetes-task-execution-controller
